services:
  hello-world:
    build: 
      context: https://github.com/zipofar/uffizzi#1479
      dockerfile: /Dockerfile
    environment:
      TEST1: test11
      
x-uffizzi:
  ingress:
    service: hello-world
    port: 80
    
  continuous_preview:
    share_to_github: true
    delete_preview_after: 96h
    delete_preview_when_image_tag_is_updated: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
